blueprints/home_page/views.py
from flask import Blueprint, session, g, render_template, redirect, url_for, flash

from .. DB import get_db
from .. auth  import login_required


bp = Blueprint('home_page', __name__, template_folder='pages')

@bp.route('/')
@login_required
def Home():
	db = get_db()
	return render_template('home_page/home.html')

blueprints/options/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session, g
import functools

from .. auth import login_required
from .. DB import get_db

from .dataclass import Options

bp = Blueprint('options', __name__, template_folder="pages", url_prefix="/options")

@bp.route('/', methods=['POST', 'GET'])
def Home():
	if request.method == 'POST':
		form = request.form

		company_name = form['company_name']

		if not company_name:
			flash("Please type company name.")
		else:
			opt = Options(db=get_db())
			for keyword in (
							'company_name', 
							'cr_prepared', 'cr_checked', 'cr_audited', 'cr_approved',
							'sales_prepared', 'sales_checked', 'sales_audited', 'sales_approved',
							'cd_prepared', 'cd_checked', 'cd_audited', 'cd_approved',
							'ap_prepared', 'ap_checked', 'ap_audited', 'ap_approved',
							'gj_prepared', 'gj_checked', 'gj_audited', 'gj_approved',
							):
				opt.get(keyword=keyword)
				opt.value = form[keyword]
				opt.save
				session[keyword] = form[keyword]

			g.company_name = company_name

			g.cr_prepared = form['cr_prepared']
			g.cr_checked = form['cr_checked']
			g.cr_audited = form['cr_audited']
			g.cr_approved = form['cr_approved']

			g.sales_prepared = form['sales_prepared']
			g.sales_checked = form['sales_checked']
			g.sales_audited = form['sales_audited']
			g.sales_approved = form['sales_approved']

			g.cd_prepared = form['cd_prepared']
			g.cd_checked = form['cd_checked']
			g.cd_audited = form['cd_audited']
			g.cd_approved = form['cd_approved']

			g.ap_prepared = form['ap_prepared']
			g.ap_checked = form['ap_checked']
			g.ap_audited = form['ap_audited']
			g.ap_approved = form['ap_approved']

			g.gj_prepared = form['gj_prepared']
			g.gj_checked = form['gj_checked']
			g.gj_audited = form['gj_audited']
			g.gj_approved = form['gj_approved']

	else:
		form = {}

		opt = Options(db=get_db())
		opt.get(keyword='company_name')
		company_name = opt.value
		form['company_name'] = "" if company_name == "Company Name" else company_name

		for keyword in (
						'cr_prepared', 'cr_checked', 'cr_audited', 'cr_approved',
						'sales_prepared', 'sales_checked', 'sales_audited', 'sales_approved',
						'cd_prepared', 'cd_checked', 'cd_audited', 'cd_approved',
						'ap_prepared', 'ap_checked', 'ap_audited', 'ap_approved',
						'gj_prepared', 'gj_checked', 'gj_audited', 'gj_approved',
						):
			opt.get(keyword=keyword)
			value = opt.value
			form[keyword] = value

	return render_template('options/home.html', form=form)

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

	<title>{{g.company_name}} v0.5</title>

	<!-- This will be deleted once all pages adopted Bootstrap 5 -->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/main.css')}}">
</head>
<body>
	<div class="flex-column">
		<header class="flex-column">
			{% include 'navbar.html' %}
		</header>
		<main class="flex-column">
			{% block content %}
			{% endblock %}		
		</main>
		<footer class="flex-column">
			{% with messages=get_flashed_messages() %}
				{% for message in messages %}
				<p class="font-red">{{message}}</p>
				{% endfor %}
			{% endwith %}
		</footer>
	</div>

	<!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/macros.html
{% macro select_field(field_name, choices, selected_id, i=None) %}
	{% if i %}
		<select name="{{i}}_{{field_name}}" class="flex-1">
	{% else %}
		<select name="{{field_name}}" class="flex-1">
	{% endif %}
			<option value="0"></option>
			{% for choice in choices %}
				{% if choice['id'] == selected_id %}
			<option value="{{choice['id']}}" selected>{{choice['name']}}</option>
				{% else %}
			<option value="{{choice['id']}}">{{choice['name']}}</option>
				{% endif %}
			{% endfor %}
		</select>
{% endmacro %}

{% macro line_entry(field_name, field_label, field_value) %}
	<div class="flex padding-20">
		<label class="width-25p">{{field_label}}</label>
		<input type="text" name="{{field_name}}" value="{{field_value}}" class="width-75p" autocomplete="off">
	</div>
{% endmacro %}

{% macro amount(field_name, number,i=None) %}
	{% if i %}
	<input type="text" name="{{i}}_{{field_name}}" value="{{number}}" class="flex-1" autocomplete="off">
	{% else %}
	<input type="text" name="{{field_name}}" value="{{number}}" class="flex-1" autocomplete="off">
	{% endif %}
{% endmacro %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid">
	  <a class="navbar-brand" href="#">{{g.company_name}}</a>
	  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNavDropdown">
		<ul class="navbar-nav">
		  <li class="nav-item">
			<a class="nav-link active" aria-current="page" href="{{url_for('home_page.Home')}}">Home</a>
		  </li>
		  <li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
			  Company Journal
			</a>
			<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			  <li><a class="dropdown-item" href="{{url_for('sales.Home')}}">Sales</a></li>
			  <li><a class="dropdown-item" href="{{url_for('cr.Home')}}">Cash Receipts</a></li>
			  <li><a class="dropdown-item" href="{{url_for('ap.Home')}}">Accounts Payable</a></li>
			  <li><a class="dropdown-item" href="{{url_for('cd.Home')}}">Cash Disbursements</a></li>
			  <li><a class="dropdown-item" href="{{url_for('gj.Home')}}">Journal Voucher</a></li>
			</ul>
		  </li>
		  <li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
			  Options
			</a>
			<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
				<li><a class="dropdown-item" href="{{url_for('account.Home')}}">Chart of Accounts</a></li>
				<li><a class="dropdown-item" href="{{url_for('vendor.Home')}}">Vendors</a></li>
				<li><a class="dropdown-item" href="{{url_for('customer.Home')}}">Customers</a></li>
				<li><a class="dropdown-item" href="{{url_for('options.Home')}}">Options</a></li>
			</ul>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" aria-current="page" href="{{url_for('auth.Logout')}}">Log Out</a>
		  </li>
		</ul>
	  </div>
	</div>
  </nav>

templates/x_base.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

	<title>{{g.company_name}} v0.5</title>

	<!-- This will be deleted once all pages adopted Bootstrap 5 -->
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/main.css')}}">
</head>
<body>
	<div class="flex-column">
		<header class="flex-column">
			{% include 'x_navbar.html' %}
		</header>
		<main class="flex-column">
			{% block content %}
			{% endblock %}		
		</main>
		<footer class="flex-column">
			{% with messages=get_flashed_messages() %}
				{% for message in messages %}
				<p class="font-red">{{message}}</p>
				{% endfor %}
			{% endwith %}
		</footer>
	</div>

	<!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/x_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid">
	  <a class="navbar-brand" href="{{url_for('home_page.Home')}}">Company X</a>
	  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNavDropdown">
		<ul class="navbar-nav">
		  <li class="nav-item">
			<a class="nav-link active" aria-current="page" href="{{url_for('x_home_page.Home')}}">Home</a>
		  </li>
		  <li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
			  Journals
			</a>
			<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			  <li><a class="dropdown-item" href="{{url_for('x_cd.Home')}}">Cash Disbursements</a></li>
			</ul>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" aria-current="page" href="{{url_for('auth.Logout')}}">Log Out</a>
		  </li>
		</ul>
	  </div>
	</div>
  </nav>